### ISSUE TITLE
MIDI effects don't work

### ISSUE THREAD

**Issue by cleary** [tidalcycles/tidal-doc#148]
I'm not sure if this should be logged as a bug here, or in tidal itself - whatever the case, this is non-functional:
https://tidalcycles.org/docs/reference/audio_effects/#midi

![image](https://user-images.githubusercontent.com/2577966/210022540-3a7aaa78-b4a1-4d00-aac1-d9339c826aa0.png)

**Comment by jqueraltmo** [comment]
Confirmed. It doesn't seem to be a counterpart on SuperDirt for those parameters. You can achieve the same effect using ccv and ccn (for example, ccn 1 is modwheel).

**Comment by jqueraltmo** [comment]
Looking more into this, it seems that these parameters come from the now obsolete tidal-midi package. I propose to just delete this section of the documentation, as the current MIDI implementation is presented elsewhere.
