### ISSUE TITLE
What to do with the blog section

### ISSUE THREAD

**Issue by jqueraltmo** [tidalcycles/tidal-doc#151]
There is a main blog section that is nearly empty (only a post by @Bubobubobubobubo).

Should we remove the whole section?

**Comment by HighHarmonics2** [comment]
If we don't actually build out a blog section - then yes, we should remove this one page. 

But I think TC should have a blog and there are many ways this could be useful.  For instance, I think it would be great to have user and/or contributor profiles posts. It would be a great way to highlight how people are using Tidal today and give people visibility. Other ideas: Post when a new release is out, Usage Tips & Tricks, open it up to the community to write blog topics. 

There was a [TidalCycles WordPress blog](https://blog.tidalcycles.org/index.html ): but the most recent entry is Aug 2020.

To me the question is should we resurrect WordPress, with many more features (and need for an admin) or just use the more basic blog capability that exists here.

**Comment by HighHarmonics2** [comment]
I added a 2nd entry to the blog - with a link to the older blog. The post formating isn't consistent with the original post - I'm not sure how to fix that. 

We can still delete this, but at least until a decision is made, there is something there.

**Comment by jqueraltmo** [comment]
Well, the blog is live again! Closing this now.
