### ISSUE TITLE
Document % in mininotation

### ISSUE THREAD

**Issue by jqueraltmo** [tidalcycles/tidal-doc#160]
"In mininotation, % denotes a ratio (/ manipulates time)" https://club.tidalcycles.org/t/fractions-variables-etc-in-mininotation/3419/2

% only appears in the mininotation page when dealing with polymetric sequences. It should be added as a symbol in its own.

**Comment by madamsapple** [comment]
This is done! [https://tidalcycles.org/docs/reference/mini_notation#ratio-shorthand](url)
