### ISSUE TITLE
repo cannot be cloned on windows due to files containing question marks 

### ISSUE THREAD

**Issue by ribon3000** [tidalcycles/tidal-doc#235]
trying to clone tidal-doc to have an offline copy for an extended period without internet access, encountering this error:

```
Cloning into 'tidal-doc'...
remote: Enumerating objects: 133659, done.
remote: Counting objects: 100% (34958/34958), done.
remote: Compressing objects: 100% (3417/3417), done.
remote: Total 133659 (delta 26344), reused 33828 (delta 25335), pack-reused 98701
Receiving objects: 100% (133659/133659), 122.67 MiB | 5.35 MiB/s, done.

Resolving deltas: 100% (67329/67329), done.
error: invalid path 'wiki-export-alternate/Translations_What_is_a_pattern?_10_en.md'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'
```

question marks are illegal in windows file paths, somehow they show up in the wiki export files though.
a workaround is to download as .zip and extract, which is fine for my use case (as an offline reference) but i suppose this will prevent windows users from participating via pull requests etc

**Comment by Zalastax** [comment]
I have faced the same issue. I also think there might be files with really long paths and files that only differ in casing, which both can cause issues on Windows. I went for using WSL2 since cleaning this up seemed substantial.

**Comment by cleary** [comment]
> I have faced the same issue. I also think there might be files with really long paths and files that only differ in casing, which both can cause issues on Windows. I went for using WSL2 since cleaning this up seemed substantial.

I did a bunch of cleanup for this a while ago with #105 

This should now be as simple as just renaming the offending files by substituting the funky characters. I can certainly take a look when I have a moment

**Comment by htor** [comment]
There are no more file names AFAIK containing `?` characters in the repo so this can be closed.

**Comment by cleary** [comment]
> There are no more file names AFAIK containing `?` characters in the repo so this can be closed:
> 
> ```shell
> find . -iname '*\?*' # reports nothing
> ```

Thanks for the reminder, I'm pretty sure I'd taken care of it all - closing
