### ISSUE TITLE
transparent image does not work well with dark mode

### ISSUE THREAD

**Issue by ndr-brt** [tidalcycles/tidal-doc#32]
The "Pattern everything" image is hardly readable in dark mode

![Screenshot from 2021-06-07 12-18-43](https://user-images.githubusercontent.com/8570990/121000455-883c4e80-c78a-11eb-918f-4d9ba48f4afa.png)

**Comment by Bubobubobubobubo** [comment]
Yes. I've seen that but it was too late. I guess that there must be an option for switching between light-mode and dark-mode images somewhere.

**Comment by htor** [comment]
This is fixed now
