### ISSUE TITLE
Search does not return any results

### ISSUE THREAD

**Issue by dwtong** [tidalcycles/tidal-doc#42]
When using the documentation search on tidalcycles.org, I am not seeing any results. This seems to be an issue with the algolia API - see developer console when searching.

<img width="1693" alt="image" src="https://user-images.githubusercontent.com/7065184/123004632-f7f83d80-d408-11eb-858a-24c9ba6ac3fc.png">

P.S. thanks a bunch for all the hard work on the new documentation! It is all super clear and helpful.

**Comment by yaxu** [comment]
Thanks, I've emailed the search provider algolia.

**Comment by yaxu** [comment]
Working now!
