### ISSUE TITLE
SuperDirt now starts automatically into atom-tidalcycles plugin

### ISSUE THREAD

**Issue by ndr-brt** [tidalcycles/tidal-doc#45]
the `start tidal` page should be updated with details on this feature on atom plugin, I took a look but seems that the structure of the page should change to be as clear as possible.

reference: https://github.com/tidalcycles/atom-tidalcycles/issues/159
documentation about: https://github.com/tidalcycles/atom-tidalcycles#superdirt

**Comment by yaxu** [comment]
Ah great, but maybe this needs to be managed a bit carefully, as many will have custom sc startups, and could be surprised by this change. Could it be better to have it default off while we are testing it?
It would also be good to see sclang output in a post window e.g. to debug problems.

**Comment by ndr-brt** [comment]
The sclang output console is already implemented and working.
Custom superdirt files could also be used.
Ok to set the default to false, I hope that it does not turn that in an unused feature.

**Comment by ndr-brt** [comment]
Ok, now it's false by default, in the meantime this issue can be closed so that can be tested before updating documentation

**Comment by yaxu** [comment]
Thanks. I've been thinking a bit more about whether it would be better for Tidal itself to start superdirt, as we move towards distributing everything together in a relocatable folder.
