### ISSUE TITLE
Choclately install command doesn't copy correctly

### ISSUE THREAD

**Issue by hellocatfood** [tidalcycles/tidal-doc#82]
The Windows Choclately install instructions includes this command as the second instruction https://tidalcycles.org/docs/getting-started/windows_install

```
 Set-ExecutionPolicy Bypass -Scope Process -Force; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))```
```
Pasting this command in powershell produces the following error:
```
Invoke-Expression : A positional parameter cannot be found that accepts argument '``'.                                  At line:1 char:52
+ ... ess -Force; iex ((New-Object System.Net.WebClient).DownloadString('ht ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Invoke-Expression], ParameterBindingException
    + FullyQualifiedErrorId : PositionalParameterNotFound,Microsoft.PowerShell.Commands.InvokeExpressionCommand
```
It appears that the extra ``` at the end is causing the issue.

In the source code for that page that code should appear as
```
>   ```shell
>    Set-ExecutionPolicy Bypass -Scope Process -Force; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))```
```

It appears that the first ```shell part of the command is being omitted

**Comment by 444B** [comment]
@hellocatfood How are you doing?
You are correct 
This issue should be resolved by the PR 90 which should place the ``` on the next line
https://github.com/tidalcycles/tidal-doc/pull/90
Tested, works

**Comment by hellocatfood** [comment]
Great! Will just wait for it to be merged

**Comment by 444B** [comment]
@hellocatfood 
This issue may be marked as resolved, the syntax changes were merged in PR90 and PR91
