### ISSUE TITLE
Uninstall instructions

### ISSUE THREAD

**Issue by hellocatfood** [tidalcycles/tidal-doc#85]
Assuming that a user has installed TidalCycles and its dependencies using the automated installs I think it would be very useful to have thorough instructions on how to completely uninstall Tidal and its dependencies, essentially reverting a system back to a "pre-tidal" state.

**Comment by Bubobubobubobubo** [comment]
What about https://tidalcycles.org/docs/getting-started/uninstalling ?

**Comment by hellocatfood** [comment]
yes, this is great, thank you!
