### ISSUE TITLE
docs homepage preview in discord (socials) has no information aside from "nutshell"

### ISSUE THREAD

**Issue by cleary** [tidalcycles/tidal-doc#89]
When you paste a link to the docs homepage into discord, the preview shows "nutshell" - it should probably have something more informative :)

![image](https://user-images.githubusercontent.com/2577966/158108235-d7109baa-aff7-4ee9-86e5-9916decc5185.png)

**Comment by jqueraltmo** [comment]
It seems already fixed. Closing

**Comment by jqueraltmo** [comment]
It seems really solved now. Keeping open as I wait for the discord cache to clear and check again.
